=== guittari/3D-Microscopy-Metadata-Standards-3D-MMS/json_schemas/schemas/experiments_schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "testing",
    "title": "testing",
    "description": "The testing category includes five metadata fields that describe the organizations providing financial support for the generation of the dataset.",
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "testingName": {
                "description": "Name of the funder.",
                "type": "string"
            },
            "testingReferenceIdentifier": {
                "description": "Alphanumeric code that uniquely identifies an individual or legal entity. Preferred identifier is ROR. ",
                "type": "array",
                "items": {
                    "type": "string"
                }
            },
            "testingReferenceIdentifierType": {
                "description": "The Identifying scheme used in fundingReferenceIdentifier.",
                "type": "array",
                "items": {
                    "type": "string",
                    "enum": ["GRID", "ISNI", "ORCID", "ROR", "RRID"]
                }
            },
            "awardNumber": {
                "description": "Funding code or project number assigned to the grant.",
                "type": "array",
                "items": {
                    "type": "string"
                }
            },
            "awardTitle": {
                "description": "Title of the grant award.",
                "type": "array",
                "items": {
                    "type": "string"
                }
            },
            "NIH": {
                "description": "Is this an NIH project?",
                "type": "string",
                "enum": ["Yes", "No"]
            }
        },
    "additionalProperties": false,
    "if": {
            "properties": {
                "NIH": {
                    "const": "Yes"
                }
            }
        },
        "then": {
            "required": ["testingName", "testingReferenceIdentifier", "testingReferenceIdentifierType", "awardNumber", "awardTitle"]
        },
        "else": {
            "required": []
        }
    }


}

=== guittari/3D-Microscopy-Metadata-Standards-3D-MMS/json_schemas/schema_tests/experiment_test.json
[
	{
		"testingName": "Your Name 1",
		"testingReferenceIdentifier": ["id1", "id2"],
		"testingReferenceIdentifierType": ["GRID", "ROR"],
		"awardNumber": ["Award1", "Award2"],
		"NIH": "No",
		"awardTitle": ["This is my title 1", "second title"]
	},
	{
		"testingName": "Your Name 2",
		"testingReferenceIdentifier": ["id1"],
		"testingReferenceIdentifierType": ["ROR"],
		"awardNumber": ["Award2"],
		"NIH": "No",
		"awardTitle": ["This is my title 2"]
	},
	{
		"NIH": "Yes",
		"testingName": "Your Name 3",
		"testingReferenceIdentifier": ["id1", "id2"],
		"testingReferenceIdentifierType": ["GRID", "ROR"],
		"awardNumber": ["Award1", "Award2"],
		"awardTitle": ["This is my title 3", "another title"]
	}
]
